### ISSUE TITLE
Deploy error - Cannot destructure property 'theme' of 'undefined'

### ISSUE THREAD

**Issue by paultalarian** [TryGhost/action-deploy-theme#45]
Hi,

I'm not able to deploy my theme anymore, as I used to do. I don't think I changed anything here. 
I'm using the online version of Ghost.

This is the error I face:
```
Error [InternalServerError]: Cannot destructure property 'theme' of 'undefined' as it is undefined.
    at /home/runner/work/_actions/TryGhost/action-deploy-theme/v1.4.0/dist/index.js:7300:33
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async main (/home/runner/work/_actions/TryGhost/action-deploy-theme/v1.4.0/dist/index.js:1572:9) {
  name: 'InternalServerError',
  context: null,
  type: 'InternalServerError',
  details: null,
  property: null,
  help: null,
  code: null,
  id: '2b380560-e096-11eb-97cd-e1a27588ea00'
}
```

This is my config:
```
name: Deploy Theme
on:
  push:
    branches:
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Deploy Ghost Theme
        uses: TryGhost/action-deploy-theme@v1.4.0
        with:
          api-url: ${{ secrets.GHOST_ADMIN_API_URL }}
          api-key: ${{ secrets.GHOST_ADMIN_API_KEY }}
```
