### ISSUE TITLE
Error on deploy with `working-directory` parameter

### ISSUE THREAD

**Issue by swidnikk** [TryGhost/action-deploy-theme#71]
I can't seem to deploy a theme located in a subdirectory — does this work?

![image](https://user-images.githubusercontent.com/275252/180786539-7a494d7f-6b02-405a-b95c-241085c60c2e.png)

![image](https://user-images.githubusercontent.com/275252/180786648-edcb4429-5aca-4e29-97cb-641cc3a79cc1.png)

**Comment by ErisDS** [comment]
Please update your version of `action-deploy-theme` to the latest version `v1.13.1` in your config. v1.5.0 did not support working directory yet.

**Comment by ErisDS** [comment]
Ignore me - I'm talking nonsense... I'll be back with a sensible answer asap.

**Comment by ErisDS** [comment]
`module_not_found` usually means packages...not files So I'm a bit confused by the error message.

There's been quite a few changes to dependencies and a minor improvement to error handling.

Could you please try again with version 1.6.0 and let me know if you still get the same error?

If that doesn't work, please try making your working directory relative, e.g. `./my-theme` as shown in the examples here: https://github.com/TryGhost/action-deploy-theme/issues/42#issuecomment-877072906

**Comment by ngeorger** [comment]
I have the same issue, I think it's related to the configuration of the checkout action. If I can fix it, I'm creating the PR ASAP and comment again here.

**Comment by ngeorger** [comment]
> I have the same issue, I think it's related to the configuration of the checkout action. If I can fix it, I'm creating the PR ASAP and comment again here.

Well, by the mentioned approach it keeps failing. Anyways, it seems to use node12 for the action, so anyways it should be related or soon-to-be-related to the deprecation of node 12 in github actions.

I recomment, in the meantime, using the manual upload or try to fix it, i'm doin g both things but I don't know how much time it could take.

Regards

**Comment by royalfig** [comment]
With the latest version of the action (1.6), are you still facing this issue?

**Comment by kotaksempit** [comment]
Im using version 1.6.3. Still got this issue.

**Comment by kotaksempit** [comment]
@royalfig Hi. Same as the original poster. 

- Error message.
```
{
  "code": "MODULE_NOT_FOUND",
  "requireStack": [
    "/home/runner/work/_actions/TryGhost/action-deploy-theme/v1.6.3/dist/index.js"
  ]
}
```

- My configuration.

```
name: Deploy Theme
on:
  push:
    branches:
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Deploy Ghost Theme
        uses: TryGhost/action-deploy-theme@v1.6.3
        with:
          api-url: ${{ secrets.GHOST_ADMIN_API_URL }}
          api-key: ${{ secrets.GHOST_ADMIN_API_KEY }}
          working-directory: ./theme
```
