### ISSUE TITLE
Canary version deprecated in admin api

### ISSUE THREAD

**Issue by Geekfish** [TryGhost/action-deploy-theme#76]
Hello 👋 

I've been trying to use this action to deploy a theme to my blog.

This is what my action yaml looks like:

```
name: Deploy Theme
on:
  push:
    branches:
      - prod
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Deploy Ghost Theme
        uses: TryGhost/action-deploy-theme@v1.6.1
        with:
          theme-name: mnml
          api-url: ${{ secrets.GHOST_ADMIN_API_URL }}
          api-key: ${{ secrets.GHOST_ADMIN_API_KEY }}
```

The github action ~fails~ raises a warning with the following error:

```
@tryghost/admin-api: The 'version' parameter has a deprecated format 'canary', please use 'v{major}.{minor}' format instead
```

I have traced this back to the admin api SDK dependency, which appears to have dropped support for 'canary' as a version.
However, this action [always defaults it to `canary`](https://github.com/TryGhost/action-deploy-theme/blob/f18e44e981c825eb71a1280a756732302c800e79/index.js).

## Suggested solution

I believe that this can be resolved as follows:

* Add an optional `with` param to specify `version`
* When provided, pass it on to the admin api.
* When not provided, omit it from the config.

Let me know what you think!
