### ISSUE TITLE
Build fails, only gives `{}`

### ISSUE THREAD

**Issue by BetaPictoris** [TryGhost/action-deploy-theme#88]
My API URL and key secretes are set, although whenever the deployment runs I get the following: 

```
Run TryGhost/action-deploy-theme@v1
  with:
    api-url: ***
    api-key: ***
{}
```

Here's my workflow: 

```yml
name: Deploy Theme
on:
  push:
    branches:
      - dev
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Deploy Ghost Theme
        uses: TryGhost/action-deploy-theme@v1
        with:
          api-url: ${{ secrets.GHOST_ADMIN_API_URL }}
          api-key: ${{ secrets.GHOST_ADMIN_API_KEY }}
```
