### ISSUE TITLE
ValidationError

### ISSUE THREAD

**Issue by zipziz** [TryGhost/action-deploy-theme#91]
//.github/workflows/main.yml
```
name: Deploy Theme
on:
  push:
    branches:
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Deploy Ghost Theme
        uses: TryGhost/action-deploy-theme@v1.6.3
        with:
          api-url: ${{ secrets.GHOST_ADMIN_API_URL }}
          api-key: ${{ secrets.GHOST_ADMIN_API_KEY }}
```

**API URL: https://domain.zip   The domain name ends with .zip**

// Error
```
adding: assets/built/ (stored 0%)
  adding: assets/built/global.css.map (deflated 69%)
  adding: assets/built/screen.css (deflated 79%)
  adding: assets/built/casper.js.map (deflated 69%)
  adding: assets/built/global.css (deflated 61%)
  adding: assets/built/screen.css.map (deflated 80%)
  adding: assets/built/casper.js (deflated 67%)
  adding: LICENSE (deflated 41%)
  adding: page.hbs (deflated 62%)
  adding: partials/ (stored 0%)
  adding: partials/post-card.hbs (deflated 70%)
  adding: partials/icons/ (stored 0%)
  adding: partials/icons/loader.hbs (deflated 47%)
  adding: partials/icons/search.hbs (deflated 31%)
  adding: partials/icons/avatar.hbs (deflated 30%)
  adding: partials/icons/fire.hbs (deflated 42%)
  adding: partials/icons/lock.hbs (deflated 58%)
  adding: partials/icons/rss.hbs (deflated 31%)
  adding: partials/icons/twitter.hbs (deflated 42%)
  adding: partials/icons/facebook.hbs (deflated 44%)
  adding: README.md (deflated 50%)
  adding: error-404.hbs (deflated 51%)
  adding: gulpfile.js (deflated 67%)
{
  "name": "ValidationError",
  "context": null,
  "type": "ValidationError",
  "details": null,
  "property": null,
  "help": null,
  "code": null,
  "id": "4a6[29](https://github.com/zipziz/iCasper/actions/runs/5240425731/jobs/9461252896#step:3:30)4b0-08ed-11ee-a729-c572fec[33](https://github.com/zipziz/iCasper/actions/runs/5240425731/jobs/9461252896#step:3:34)3f7",
  "ghostErrorCode": null
}
```
